# -*- coding: utf-8 -*-
"""Helper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y__fxDB6RbMLmbCqy4kRq2YMMJZ2batj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

class Helper:

  def __init__(self, data):
    self.data = data


  def sigmoid(x):
    return 1 / (1 + math.exp(-x))

  def get_states(self, at_time, window_size):

      d = at_time - window_size +1

      block = self.data[d:t+1] if d  >= 0  else  - d * [data[0]] + data[0:at_time+1]

      res = []

      for i in range(n-1):

          res.append(sigmoid(block[i+1] - block[i]))

      return np.array([res])



  def plot(data_input, states_buy, states_sell, profit):

      fig = plt.figure(fig_size = (15,5))
      plt.plot(data_input, color = 'r', lw = 2.)
      plt.plot(data_input, '^', markersize = 10, color = 'm', label = 'Buying signal', markevery = states_buy)
      plt.plot(data_input, 'v', markersize = 10, color = 'k', label = 'selling signal', markevery = states_sell)
      plt.title('Total gains: %f'%(profit))
      plt.legend()
      plt.show()